package com.mygdx.game;

public class GestorImagen {
	//URLs de todas las pantallas del juego
	public static final String URL_PANTALLA_TITULO_SUSPENSE = "Imagenes/Escenarios/Titulo.png";
	public static final String URL_PANTALLA_TITULO = "Imagenes/EscenariosSinSuspense/tituloSin.png";
	public static final String URL_PANTALLA_PASILLO = "Imagenes/Escenarios/pruebaPasillo.png";
	public static final String URL_PANTALLA_INTRO = "Imagenes/pruebaFondoPasillo.png";
	public static final String URL_PANTALLA_ATICO = "Imagenes/Pantallas/Desvаn-neutro.jpg";
	public static final String URL_PANTALLA_BIBLIOTECA = "Imagenes/Pantallas/Biblioteca-neutro.jpg";
	public static final String URL_PANTALLA_DORMITORIO = "Imagenes/Pantallas/Dormitorio-neutro.jpg";
	public static final String URL_PANTALLA_SALON = "Imagenes/Pantallas/Salon-neutro.jpg";
	public static final String URL_PANTALLA_SOTANO = "Imagenes/Pantallas/Sotano-neutro.jpg";
	public static final String URL_PANTALLA_ATICO_SUSPENSE = "Imagenes/Pantallas/Desvаn-suspense.jpg";
	public static final String URL_PANTALLA_BIBLIOTECA_SUSPENSE = "Imagenes/Pantallas/Biblioteca-suspense.jpg";
	public static final String URL_PANTALLA_DORMITORIO_SUSPENSE = "Imagenes/Pantallas/Dormitorio-suspense.jpg";
	public static final String URL_PANTALLA_SALON_SUSPENSE = "Imagenes/Pantallas/Salon-suspense.jpg";
	public static final String URL_PANTALLA_SOTANO_SUSPENSE = "Imagenes/Pantallas/Sotano-suspense.jpg";
	public static final String URL_PANTALLA_ARMA = "Imagenes/pantallaArma.png";
	public static final String URL_PANTALLA_ASESINO = "Imagenes/pantallaAsesino.png";
	public static final String URL_PANTALLA_INVENTARIO = "Imagenes/Escenarios/inventario.png";
	public static final String URL_PANTALLA_FINAL = "Imagenes/final.png";
	
	//URLs de todos los botones del juego
	public static final String URL_BOTON_ABAJO = "Imagenes/Botones/botonAbajo.png";
	public static final String URL_BOTON_ACEPTAR_COMBINAR = "Imagenes/Botones/botonAceptarCombinar.png";
	public static final String URL_BOTON_ACEPTAR_COMBINAR_DES = "Imagenes/Botones/Desactivados/botonAceptarCombinarDesactivado.png";
	public static final String URL_BOTON_ARRIBA = "Imagenes/Botones/botonArriba.png";
	public static final String URL_BOTON_CANCELAR_COMBINAR = "Imagenes/Botones/botonCancelarCombinar.png";
	public static final String URL_BOTON_CANCELAR_COMBINAR_DES = "Imagenes/Botones/Desactivados/botonCancelarCombinarDesactivado.png";
	public static final String URL_BOTON_CERRAR_INVENTARIO = "Imagenes/Botones/botonSalirInventario.png";
	public static final String URL_BOTON_CERRAR_INVENTARIO_DES = "Imagenes/Botones/Desactivados/botonSalirInventarioDesactivado.png";
	public static final String URL_BOTON_COMBINAR_OBJETO = "Imagenes/Botones/botonCombinar.png";
	public static final String URL_BOTON_CONTINUAR = "Imagenes/Botones/botonContinuar.png";
	public static final String URL_BOTON_CONVERSACION = "Imagenes/Botones/botonConversacion.png";
	public static final String URL_BOTON_CONVERSARION_DES = "Imagenes/Botones/Desactivados/botonConversacionDesactivado.png";
	public static final String URL_BOTON_DERECHA = "Imagenes/Botones/botonDerecha.png";
	public static final String URL_BOTON_FIN_CONVERSACION_SUSPENSE = "Imagenes/Botones/botonFinConversacionSuspense.png";
	public static final String URL_BOTON_FIN_CONVERSACION = "Imagenes/Botones/botonFinConversacionSinSuspense.png";
	public static final String URL_BOTON_INICIO_SUSPENSE = "Imagenes/Botones/botonInicio.png";
	public static final String URL_BOTON_INICIO = "Imagenes/Botones/botonNuevaSin.png";
	public static final String URL_BOTON_INVENTARIO = "Imagenes/Botones/botonInventario.png";
	public static final String URL_BOTON_INVESTIGAR = "Imagenes/Botones/botonInvestigar.png";
	public static final String URL_BOTON_INVESTIGAR_DES = "Imagenes/Botones/Desactivados/botonInvestigarDesactivado.png";
	public static final String URL_BOTON_IZQUIERDA = "Imagenes/Botones/botonIzquierda.png";
	public static final String URL_BOTON_PUERTA_HABITACION = "Imagenes/Botones/botonPuertaHabitacion.png";
	public static final String URL_BOTON_PUERTA_HABITACION_DES = "Imagenes/Botones/Desactivados/botonPuertaHabitacionDesactivado.png";
	public static final String URL_BOTON_PUERTA_PASILLO = "Imagenes/Botones/botonPuerta.png";
	public static final String URL_BOTON_PUERTA_PASILLO_DES = "Imagenes/Botones/Desactivados/botonPuertaDesactivado.png";
	public static final String URL_BOTON_SALIR_SUSPENSE = "Imagenes/Botones/botonSalir.png";
	public static final String URL_BOTON_SALIR = "Imagenes/Botones/botonSalirSin.png";
	public static final String URL_BOTON_SIGUIENTE_CONVERSACION = "Imagenes/Botones/sigConv.png";
	public static final String URL_BOTON_CREDITOS = "Imagenes/Botones/botonCreditos.png";
	
	//URLs de todos los personajes del juego
	public static final String URL_ANCIANA_SUSPENSE = "Imagenes/Personajes/Anciana-suspense.png";
	public static final String URL_ANCIANA = "Imagenes/Personajes/Anciana-neutro.png";
	public static final String URL_HOMBRE_SUSPENSE = "Imagenes/Personajes/Hombre-suspense.png";
	public static final String URL_HOMBRE = "Imagenes/Personajes/Hombre-neutro.png";
	public static final String URL_JOVEN_SUSPENSE = "Imagenes/Personajes/Joven-suspense.png";
	public static final String URL_JOVEN = "Imagenes/Personajes/Joven-neutro.png";
	public static final String URL_MUJER_SUSPENSE = "Imagenes/Personajes/Mujer-suspense.png";
	public static final String URL_MUJER = "Imagenes/Personajes/Mujer-neutro.png";
	public static final String URL_CHICA_SUSPENSE = "Imagenes/Personajes/Chica-suspense.png";
	public static final String URL_CHICA = "Imagenes/Personajes/Chica-neutro.png";
	
	//URLs de todos los objetos del juego
	public static final String URL_SERPIENTE = "";
	public static final String URL_MONEDA = "";
	public static final String URL_CALAVERA = "";
	public static final String URL_CARAMELO = "";
	public static final String URL_CUADRO = "";
	public static final String URL_ESPEJO = "";
	public static final String URL_NAVAJA = "";
	public static final String URL_BOTELLA = "";
	public static final String URL_ATAUD = "";
	public static final String URL_BOLIGRAFO = "";
	public static final String URL_MASCARA = "";
	public static final String URL_LIBRO = "";
	public static final String URL_BASURA = "";
	public static final String URL_ANILLO = "";
	public static final String URL_ESCOPETA = "";
	public static final String URL_JOYA = "";
	public static final String URL_CIGARRILLOS = "";
	public static final String LLAVE = "";
	public static final String PISTOLA = "";
	public static final String ZAPATO = "";
	public static final String VENENO = "";
	public static final String AZUCAR = "";
	public static final String DAGA = "";
	public static final String CAFE = "";
	public static final String JAULA = "";
	public static final String BOMBILLA = "";
}

